<a href="https://colab.research.google.com/github/RodrigoEslava/Ms_project/blob/main/predicet_edges_09_04_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Libraries/ Modules

import pandas as pd
import numpy as np
from pandas import Series, DataFrame

from sklearn.svm import SVC

from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import  cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import roc_auc_score, confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import make_scorer
from sklearn import metrics


import lightgbm as lgb
import xgboost as xgb


import warnings
warnings.filterwarnings('ignore')

In [ ]:
#opening data
df_1 = pd.read_csv("/content/drive/MyDrive/USP/vectors_input_ml__from_D50_emb.txt", header = None, sep = " ")
df_1 = pd.DataFrame(data = df_1)

df_1

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,102
0,114787,375519,-0.218339,0.051927,0.433674,0.379050,-0.303076,-0.712676,0.246733,-0.184586,...,0.582748,-0.093185,0.197429,0.196804,0.126834,0.829950,-0.282973,-0.087741,0.356805,1
1,114787,285613,-0.218339,0.051927,0.433674,0.379050,-0.303076,-0.712676,0.246733,-0.184586,...,0.718021,0.411645,1.058466,0.447975,-0.278689,0.018391,0.704961,0.852890,-0.188985,1
2,114787,7448,-0.218339,0.051927,0.433674,0.379050,-0.303076,-0.712676,0.246733,-0.184586,...,0.226083,0.141008,0.697741,-0.052053,0.008418,-0.203921,-0.329396,0.021598,-0.066564,1
3,114787,4914,-0.218339,0.051927,0.433674,0.379050,-0.303076,-0.712676,0.246733,-0.184586,...,-0.330690,-0.056626,0.277379,0.462125,0.510014,0.564205,0.191713,-0.279282,-0.163813,1
4,114787,51343,-0.218339,0.051927,0.433674,0.379050,-0.303076,-0.712676,0.246733,-0.184586,...,0.249835,0.005776,0.115309,0.447104,0.288978,0.295816,-0.003162,0.428033,-0.059167,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431217,90737,339855,-0.299822,0.073110,-0.012066,0.064782,-0.182190,-0.198826,0.568433,0.386396,...,-0.193971,0.069791,-1.148958,0.031849,0.104723,0.750949,-0.188681,0.895546,0.247883,0
1431218,310,4325,-0.090669,0.012640,-0.389824,0.037508,0.220777,-0.577209,0.255316,0.344268,...,-0.227559,0.906436,0.406652,1.064613,0.322546,0.138281,-0.324130,0.015952,0.281831,0
1431219,6585,8079,-0.018634,0.060265,0.285404,-0.016298,0.412535,0.123264,0.647300,0.153524,...,-0.121844,-0.396580,0.522469,0.664378,0.126808,0.028348,0.072730,0.781687,0.404790,0
1431220,4881,63899,0.376214,0.035402,-0.026258,0.173349,0.416900,-0.438496,0.514068,0.107551,...,0.096137,0.026553,0.933624,0.594865,0.385034,-0.439389,0.039829,0.344956,-0.593266,0
1431221,55556,8226,0.268746,-0.073208,-1.060397,0.506022,-0.044204,-0.704936,0.528931,-0.586521,...,0.250320,-0.197718,-0.567409,1.264782,-0.125973,0.972720,-1.131025,0.405513,0.303397,0

In [ ]:
# Separating the values ​​of X and y
X = df_1[df_1.columns[2:102]]
y = df_1[df_1.columns[102:]]

y

         102
0          1
1          1
2          1
3          1
4          1
...      ...
1431217    0
1431218    0
1431219    0
1431220    0
1431221    0

[1431222 rows x 1 columns]

In [ ]:
X

,2,3,4,5,6,7,8,9,10,11,...,92,93,94,95,96,97,98,99,100,101
0,-0.218339,0.051927,0.433674,0.379050,-0.303076,-0.712676,0.246733,-0.184586,-0.253981,0.268568,...,-0.078732,0.582748,-0.093185,0.197429,0.196804,0.126834,0.829950,-0.282973,-0.087741,0.356805
1,-0.218339,0.051927,0.433674,0.379050,-0.303076,-0.712676,0.246733,-0.184586,-0.253981,0.268568,...,0.178062,0.718021,0.411645,1.058466,0.447975,-0.278689,0.018391,0.704961,0.852890,-0.188985
2,-0.218339,0.051927,0.433674,0.379050,-0.303076,-0.712676,0.246733,-0.184586,-0.253981,0.268568,...,0.197277,0.226083,0.141008,0.697741,-0.052053,0.008418,-0.203921,-0.329396,0.021598,-0.066564
3,-0.218339,0.051927,0.433674,0.379050,-0.303076,-0.712676,0.246733,-0.184586,-0.253981,0.268568,...,0.758105,-0.330690,-0.056626,0.277379,0.462125,0.510014,0.564205,0.191713,-0.279282,-0.163813
4,-0.218339,0.051927,0.433674,0.379050,-0.303076,-0.712676,0.246733,-0.184586,-0.253981,0.268568,...,0.219192,0.249835,0.005776,0.115309,0.447104,0.288978,0.295816,-0.003162,0.428033,-0.059167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431217,-0.299822,0.073110,-0.012066,0.064782,-0.182190,-0.198826,0.568433,0.386396,-0.104465,0.274835,...,0.041359,-0.193971,0.069791,-1.148958,0.031849,0.104723,0.750949,-0.188681,0.895546,0.247883
1431218,-0.090669,0.012640,-0.389824,0.037508,0.220777,-0.577209,0.255316,0.344268,0.011421,-0.112356,...,0.290241,-0.227559,0.906436,0.406652,1.064613,0.322546,0.138281,-0.324130,0.015952,0.281831
1431219,-0.018634,0.060265,0.285404,-0.016298,0.412535,0.123264,0.647300,0.153524,0.290880,0.136970,...,0.166483,-0.121844,-0.396580,0.522469,0.664378,0.126808,0.028348,0.072730,0.781687,0.404790
1431220,0.376214,0.035402,-0.026258,0.173349,0.416900,-0.438496,0.514068,0.107551,-0.706025,-0.275096,...,0.608079,0.096137,0.026553,0.933624,0.594865,0.385034,-0.439389,0.039829,0.344956,-0.593266
1431221,0.268746,-0.073208,-1.060397,0.506022,-0.044204,-0.704936,0.528931,-0.586521,-0.035635,0.189441,...,1.055320,0.250320,-0.197718,-0.567409,1.264782,-0.125973,0.972720,-1.131025,0.405513,0.303397

In [ ]:
# Separating the training data and test data
X_training, X_test, y_training, y_test = train_test_split(X, y, test_size = 0.3, random_state = 7, stratify = y)




#defining values to folds

num_folds = 10
seed = 7
kf = KFold(n_splits=num_folds, shuffle = True, random_state=seed)


#scoring methods

custom_scorer = {'accuracy': make_scorer(accuracy_score),
                 'precision': make_scorer(precision_score, average='macro'),
                 'recall': make_scorer(recall_score, average='macro'),
                 'f1': make_scorer(f1_score, average='macro'),
                 'roc_auc' : make_scorer(roc_auc_score, average='macro')
                 }

In [ ]:
#Classifier multiples evaluation metrics

lgbm_classifier = lgb.LGBMClassifier(n_jobs=10)
cv_results = cross_validate(lgbm_classifier, X_training,  y_training, cv = kf, scoring=custom_scorer, n_jobs=10)

print(f"Resultados do CV: {cv_results}")

# Print the results
print("Precision: ", cv_results['test_precision'].mean())
print("Recall: ", cv_results['test_recall'].mean())
print("F1 Score: ", cv_results['test_f1'].mean())
print("ROC AUC: ", cv_results['test_roc_auc'].mean())
print("Accuracy: ", cv_results['test_accuracy'].mean())

Resultados do CV: {'fit_time': array([1151.55421185, 1158.61853695, 1152.57814908, 1158.20385265,
       1158.55302787, 1152.10666633, 1156.4592061 , 1157.01871514,
       1153.03873301, 1151.5109992 ]), 'score_time': array([2.29833865, 0.42096353, 1.53102779, 0.5126543 , 0.41476583,
       1.67792892, 1.12312937, 0.79052401, 1.29352117, 2.33659482]), 'test_accuracy': array([0.86511089, 0.86451201, 0.86459186, 0.86561995, 0.86214641,
       0.863782  , 0.8636223 , 0.86505964, 0.86557868, 0.86396167]), 'test_precision': array([0.8651726 , 0.86456524, 0.86462887, 0.86565182, 0.86221324,
       0.86385517, 0.86365523, 0.86510535, 0.86563793, 0.86399913]), 'test_recall': array([0.86513384, 0.86450008, 0.86458604, 0.86562771, 0.86216374,
       0.86375807, 0.86363805, 0.86507408, 0.8655776 , 0.86392579]), 'test_f1': array([0.86510903, 0.86450388, 0.86458694, 0.86561846, 0.86214333,
       0.86376832, 0.86362164, 0.86505795, 0.86557299, 0.86394479]), 'test_roc_auc': array([0.86513384, 0.86450008, 0.86458604, 0.86562771, 0.86216374,
       0.86375807, 0.86363805, 0.86507408, 0.8655776 , 0.86392579])}
Precision:  0.8644484584472876
Recall:  0.8643984984091858
F1 Score:  0.8643927339111619
ROC AUC:  0.8643984984091858
Accuracy:  0.8643985407185555

In [ ]:
# Fit 
lgbm_classifier.fit(X_training,  y_training)


# Predict test
predict_class_test = lgbm_classifier.predict(X_test)
print(f"predict_class_test: {predict_class_test}")
predict_class_test = pd.DataFrame(data=predict_class_test)


predict_class_prob_test = lgbm_classifier.predict_proba(X_test)
print(f"predict_class_prob_test: {predict_class_prob_test}")
predict_class_prob_test = pd.DataFrame(data=predict_class_prob_test)


# Confusion Matrix
confusion_matrix = confusion_matrix(y_test, lgbm_classifier.predict(X_test))
print(f"confusion_matrix: {confusion_matrix}")



# Score list

f1_score_m = f1_score(y_test, predict_class_test, average='macro')
roc_auc_m = roc_auc_score(y_test, lgbm_classifier.predict_proba(X_test)[:, 1], average='macro')


print(f"f1 : {f1_score_m}, roc: {roc_auc_m}")

predict_class_test: [1 0 1 ... 0 1 0]
predict_class_prob_test: [[0.33641424 0.66358576]
 [0.83857525 0.16142475]
 [0.29583867 0.70416133]
 ...
 [0.69487818 0.30512182]
 [0.06426201 0.93573799]
 [0.77563741 0.22436259]]
confusion_matrix: [[184623  30060]
 [ 28219 186465]]
f1 : 0.8642651330670096, roc: 0.9413924869300279

In [ ]:
#lgbm_classifier.save_model('/content/drive/MyDrive/USP/Projeto Mestrado/pipeline completo/lgbm_classifier.txt')
lgbm_classifier.booster_.save_model('/content/drive/MyDrive/USP/Projeto Mestrado/pipeline completo/lgbm_classifier_booster.txt')

In [ ]:
# Predict edges

#opening data to predict
df_2 = pd.read_csv("/content/drive/MyDrive/USP/Projeto Mestrado/pipeline completo/df_finais/input_to_predict_redone_09_04_2023.csv", sep =  " ")
df_2 = pd.DataFrame(data = df_2)

df_2

,1,2,3,4,5,6,7,8,9,10,...,93,94,95,96,97,98,99,100,pain_genes,pred_genes
0,-0.440928,0.010586,-0.435278,0.038953,-0.11626,-1.236842,-0.108285,0.465328,-0.700119,0.246238,...,0.683625,-0.205395,0.331953,-0.279398,-0.353793,-0.529386,-0.163674,0.602258,18,8481
1,-0.440928,0.010586,-0.435278,0.038953,-0.11626,-1.236842,-0.108285,0.465328,-0.700119,0.246238,...,0.350561,-0.381889,0.407751,-0.156612,-0.226207,-0.742283,-0.188091,0.626081,18,3301
2,-0.440928,0.010586,-0.435278,0.038953,-0.11626,-1.236842,-0.108285,0.465328,-0.700119,0.246238,...,0.205839,-0.036335,0.426904,0.158833,-0.428774,-0.033264,-0.380717,0.077926,18,8487
3,-0.440928,0.010586,-0.435278,0.038953,-0.11626,-1.236842,-0.108285,0.465328,-0.700119,0.246238,...,0.645431,-0.526980,0.794016,-0.253569,0.810793,-0.640734,0.272748,-0.097868,18,8484
4,-0.440928,0.010586,-0.435278,0.038953,-0.11626,-1.236842,-0.108285,0.465328,-0.700119,0.246238,...,0.660858,-0.522293,1.649438,-0.203488,0.148696,-0.317625,-0.168494,0.447649,18,1295
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6563515,0.409335,-0.166936,0.593236,0.872901,-0.03825,-0.015421,0.848584,-0.351987,-0.517368,-0.059001,...,-0.282596,0.098423,0.202695,0.090739,-0.376544,0.083988,-0.107363,-0.158526,729230,91894
6563516,0.409335,-0.166936,0.593236,0.872901,-0.03825,-0.015421,0.848584,-0.351987,-0.517368,-0.059001,...,-0.116343,-0.045316,0.259860,0.263672,-0.399213,0.051540,0.421198,0.077854,729230,6794
6563517,0.409335,-0.166936,0.593236,0.872901,-0.03825,-0.015421,0.848584,-0.351987,-0.517368,-0.059001,...,-0.149806,0.630066,0.404723,-0.259313,0.111323,-0.165137,-0.066624,0.053573,729230,119369
6563518,0.409335,-0.166936,0.593236,0.872901,-0.03825,-0.015421,0.848584,-0.351987,-0.517368,-0.059001,...,-0.136435,0.752556,0.550248,-0.059564,0.064050,-0.194645,-0.226479,-0.395458,729230,57486
6563519,0.409335,-0.166936,0.593236,0.872901,-0.03825,-0.015421,0.848584,-0.351987,-0.517368,-0.059001,...,-0.316120,0.391087,0.467723,0.221620,-0.156128,-0.437360,-0.351844,0.016195,729230,387601

In [ ]:
X_edges = df_2[df_2.columns[:100]]

X_edges

,1,2,3,4,5,6,7,8,9,10,...,91,92,93,94,95,96,97,98,99,100
0,-0.440928,0.010586,-0.435278,0.038953,-0.11626,-1.236842,-0.108285,0.465328,-0.700119,0.246238,...,0.184081,-0.333196,0.683625,-0.205395,0.331953,-0.279398,-0.353793,-0.529386,-0.163674,0.602258
1,-0.440928,0.010586,-0.435278,0.038953,-0.11626,-1.236842,-0.108285,0.465328,-0.700119,0.246238,...,0.200914,-0.219695,0.350561,-0.381889,0.407751,-0.156612,-0.226207,-0.742283,-0.188091,0.626081
2,-0.440928,0.010586,-0.435278,0.038953,-0.11626,-1.236842,-0.108285,0.465328,-0.700119,0.246238,...,0.797625,-0.651433,0.205839,-0.036335,0.426904,0.158833,-0.428774,-0.033264,-0.380717,0.077926
3,-0.440928,0.010586,-0.435278,0.038953,-0.11626,-1.236842,-0.108285,0.465328,-0.700119,0.246238,...,0.286999,-0.316976,0.645431,-0.526980,0.794016,-0.253569,0.810793,-0.640734,0.272748,-0.097868
4,-0.440928,0.010586,-0.435278,0.038953,-0.11626,-1.236842,-0.108285,0.465328,-0.700119,0.246238,...,0.755649,-0.619018,0.660858,-0.522293,1.649438,-0.203488,0.148696,-0.317625,-0.168494,0.447649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6563515,0.409335,-0.166936,0.593236,0.872901,-0.03825,-0.015421,0.848584,-0.351987,-0.517368,-0.059001,...,0.267991,-0.145776,-0.282596,0.098423,0.202695,0.090739,-0.376544,0.083988,-0.107363,-0.158526
6563516,0.409335,-0.166936,0.593236,0.872901,-0.03825,-0.015421,0.848584,-0.351987,-0.517368,-0.059001,...,0.262664,0.277268,-0.116343,-0.045316,0.259860,0.263672,-0.399213,0.051540,0.421198,0.077854
6563517,0.409335,-0.166936,0.593236,0.872901,-0.03825,-0.015421,0.848584,-0.351987,-0.517368,-0.059001,...,0.547410,0.899515,-0.149806,0.630066,0.404723,-0.259313,0.111323,-0.165137,-0.066624,0.053573
6563518,0.409335,-0.166936,0.593236,0.872901,-0.03825,-0.015421,0.848584,-0.351987,-0.517368,-0.059001,...,0.446059,0.010872,-0.136435,0.752556,0.550248,-0.059564,0.064050,-0.194645,-0.226479,-0.395458
6563519,0.409335,-0.166936,0.593236,0.872901,-0.03825,-0.015421,0.848584,-0.351987,-0.517368,-0.059001,...,0.393573,0.291635,-0.316120,0.391087,0.467723,0.221620,-0.156128,-0.437360,-0.351844,0.016195

In [ ]:
predict_edges = lgbm_classifier.predict(X_edges)
#print(f"predict_edges_final: {predict_edges}")
predict_edges = pd.DataFrame(data=predict_edges)

predict_edges_prob = lgbm_classifier.predict_proba(X_edges)
#print(f"predict_edges_prob_final: {predict_edges_prob}")
predict_edges_prob = pd.DataFrame(data=predict_edges_prob)


# Save final results

# creating pain genes column
pain_genes = list()
pain_genes = pd.DataFrame(pain_genes)
pain_genes['pain_genes'] = df_2['pain_genes']

#creating predicted gene column

pred_genes = list()
pred_genes = pd.DataFrame(pred_genes)
pred_genes['pred_genes'] = df_2["pred_genes"]

final_result = list()
final_result = pd.DataFrame(final_result)
final_result = pd.concat([predict_edges, predict_edges_prob, pain_genes, pred_genes], axis=1)

final_result

         0         0         1  pain_genes  pred_genes
0        0  0.590796  0.409204          18        8481
1        0  0.614848  0.385152          18        3301
2        0  0.599485  0.400515          18        8487
3        0  0.769529  0.230471          18        8484
4        0  0.630380  0.369620          18        1295
...     ..       ...       ...         ...         ...
6563515  0  0.767562  0.232438      729230       91894
6563516  0  0.801911  0.198089      729230        6794
6563517  0  0.606284  0.393716      729230      119369
6563518  0  0.835936  0.164064      729230       57486
6563519  0  0.746674  0.253326      729230      387601

[6563520 rows x 5 columns]

In [ ]:
# Save final rresult
final_result.to_csv("/content/drive/MyDrive/USP/Projeto Mestrado/pipeline completo/predicted_interactions_09_04_2023.csv", sep = " " )

In [ ]:
# Save results final
result_final = []
result_final = pd.DataFrame(data=result_final)

result_final["class_pred"] = predict_edges[0]


result_final["prob_0"] = predict_edges_prob[0]

result_final["prob_1"] = predict_edges_prob[1]

result_final["pain_genes"] = df_2["pain"]
result_final

In [ ]:
gene_2 = df_2["gene_2"]
gene_2 = pd.DataFrame(data = gene_2)
gene_2.to_csv("gene_2_do_predicted_edges.csv", sep = " ")

In [ ]:
gene_2

         gene_2
0          8481
1          3301
2          8487
3          8484
4          1295
...         ...
6563859   91894
6563860    6794
6563861  119369
6563862   57486
6563863  387601

[6563520 rows x 1 columns]

In [ ]:
result_final["gene_1"]  = df_2["gene_1"]

In [ ]:


result_final["gene_2"] = gene_2["gene_2"]

In [ ]:
result_final["class_pred"].sum()
#1055534

1055534

In [ ]:
result_final

         class_pred    prob_0    prob_1    gene_1
0                 0  0.500123  0.499877      18.0
1                 0  0.555853  0.444147      18.0
2                 0  0.679216  0.320784      18.0
3                 0  0.742758  0.257242      18.0
4                 0  0.757652  0.242348      18.0
...             ...       ...       ...       ...
6563515           0  0.790457  0.209543  729230.0
6563516           0  0.692485  0.307515  729230.0
6563517           0  0.589840  0.410160  729230.0
6563518           0  0.721152  0.278848  729230.0
6563519           0  0.847330  0.152670  729230.0

[6563520 rows x 4 columns]

In [ ]:
predict_edges_prob

                0         1
0        0.500123  0.499877
1        0.555853  0.444147
2        0.679216  0.320784
3        0.742758  0.257242
4        0.757652  0.242348
...           ...       ...
6563515  0.790457  0.209543
6563516  0.692485  0.307515
6563517  0.589840  0.410160
6563518  0.721152  0.278848
6563519  0.847330  0.152670

[6563520 rows x 2 columns]

In [ ]:

# Save results final
result_final.to_csv("predicted_edges_no_gene_2.csv", sep = " " )